import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/components/theme-provider";
import SideNavBar from "@/components/shared/SideNavBar";
import TopNavBar from "@/components/shared/TopNavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          disableTransitionOnChange
        >
          <section className="">
            <TopNavBar />
            <div className="flex flex-row items-center min-h-screen">
              <div className="p-2">
                <SideNavBar />
              </div>
              <div className="w-full min-screen justify-center items-center flex">
                {children}
              </div>
            </div>
          </section>
        </ThemeProvider>
      </body>
    </html>
  );
}
